#!/usr/bin/env python3
"""Generate the cross-language parity fixture for the C# port.

src/PseudoPBR/PbrMapGenerator.cs is a port of pbrgen.py, and a silent
divergence between the tool people tune with and the code that actually ships
is the worst outcome available. This writes a small, diffable JSON summary of
this implementation's output on a fixed input; tools/smoketest recomputes the
same thing in C# and asserts they agree.

The input is defined by an arithmetic formula, NOT by a random number
generator: RNG streams differ between languages, so a formula is the only way
both sides can build a bit-identical input independently.

Regenerate with:  python3 tools/pbrgen/parity_fixture.py
"""

from __future__ import annotations

import json
import math
import pathlib

import numpy as np

import pbrgen

WIDTH = 24
HEIGHT = 16
OUT = pathlib.Path(__file__).parent / "parity_fixture.json"


def build_input():
    """Deterministic sRGB texture + alpha. Must match the C# side exactly."""
    r = np.zeros((HEIGHT, WIDTH))
    g = np.zeros((HEIGHT, WIDTH))
    b = np.zeros((HEIGHT, WIDTH))
    a = np.ones((HEIGHT, WIDTH))

    for y in range(HEIGHT):
        for x in range(WIDTH):
            r[y, x] = 0.5 + 0.4 * math.sin(x * 0.7 + y * 0.3)
            g[y, x] = 0.5 + 0.4 * math.sin(x * 0.31 + y * 0.91 + 1.3)
            b[y, x] = 0.5 + 0.4 * math.sin(x * 1.13 - y * 0.17 + 2.7)
            # A transparent block, so the alpha-masking path is covered too.
            if 3 <= x < 8 and 2 <= y < 6:
                a[y, x] = 0.0

    return np.clip(r, 0, 1), np.clip(g, 0, 1), np.clip(b, 0, 1), a


def summarise(name, values):
    """A few order-independent statistics plus fixed probes.

    Statistics alone would miss a transposed or mirrored map; the probes pin
    specific texels so an axis flip cannot pass.
    """
    flat = np.asarray(values, dtype=np.float64).ravel()
    probes = [int(i * len(flat) / 7.0) for i in range(7)]
    return {
        "name": name,
        "count": int(flat.size),
        "mean": round(float(flat.mean()), 10),
        "min": round(float(flat.min()), 10),
        "max": round(float(flat.max()), 10),
        "sum": round(float(flat.sum()), 8),
        "probes": {str(i): round(float(flat[i]), 10) for i in probes},
    }


def main() -> int:
    r, g, b, a = build_input()

    rgb_linear = np.dstack([
        pbrgen.srgb_to_linear(r),
        pbrgen.srgb_to_linear(g),
        pbrgen.srgb_to_linear(b),
    ])
    lum = pbrgen.luminance(rgb_linear)

    valid = a > pbrgen.ALPHA_CUTOFF
    if valid.any() and not valid.all():
        lum = np.where(valid, lum, lum[valid].mean())

    normal = pbrgen.generate_normal_from_luminance(lum, pbrgen.NORMAL_STRENGTH, True)
    rough = pbrgen.generate_roughness_from_variance(lum, 1, True)
    spec = pbrgen.generate_spec_mask_from_colour_average(rgb_linear, a, tiling=True)

    fixture = {
        "_comment": "Generated by tools/pbrgen/parity_fixture.py. Do not hand-edit.",
        "width": WIDTH,
        "height": HEIGHT,
        "constants": {
            "roughness_std_reference": pbrgen.ROUGHNESS_STD_REFERENCE,
            "roughness_floor": pbrgen.ROUGHNESS_FLOOR,
            "spec_region_threshold": pbrgen.SPEC_REGION_THRESHOLD,
            "spec_inclusion_max_area": pbrgen.SPEC_INCLUSION_MAX_AREA,
            "spec_inclusion_boost": pbrgen.SPEC_INCLUSION_BOOST,
            "alpha_cutoff": pbrgen.ALPHA_CUTOFF,
            "normal_strength": pbrgen.NORMAL_STRENGTH,
        },
        "maps": [
            summarise("normal", normal),
            summarise("roughness", rough),
            summarise("spec", spec),
        ],
    }

    OUT.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"wrote {OUT}")
    for m in fixture["maps"]:
        print(f"  {m['name']:10} mean={m['mean']:.6f} min={m['min']:.6f} max={m['max']:.6f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
